herdius/herdius-blockchain-api

- client.go
The API repo is using a deprecated dependency.
Update to the newer repository.
> Remove dev dependency

- handler/init.go
> these vars are legacy

- README.md
> Add a bit of documentation on GET /account

- deployment/start_server.sh
I broke CICD by changing the flagging system but not updating the CICD scripts
Update the CICD scripts
Very difficult to test until actually implemented in CICD scripts
> cicd needs staging flag

- clientjs/.gitignore
- clientjs/README.md
- clientjs/package.json
- clientjs/src/lib/secp256k1.ts
- clientjs/src/main.ts
- clientjs/src/models/proto.d.ts
- clientjs/src/models/proto.js
- clientjs/src/proto.js
- clientjs/tsconfig.json
- config/config.go
JS client to send Herdius Tx
Asana Link: 
client is sending Tx successfully
Added readme for secp256k2 lib
> Clientjs, Herdius JS client

- deployment/start_server.sh
Breaking - API doesn't have a gopath
Provide a gopath
> Need a gopath to deploy

- handler/tx.go
Post/Update Tx panic.
Save/Update to db only when it's available
Passed.
> handler: save/update tx only when db not nil

- config/config.go
DB conn is using wrong `dbpassword`
`dbpassword` -> `password`
Passed.
> config: fix postgres conn string

- handler/tx.go
Get Txs from store return non-nil error when no tx founds.
Query core if len(txs) == 0
Passed.
> handler: when len(txs) == 0, query from core

- handler/tx.go
Same logic in https://github.com/herdius/herdius-blockchain-api/pull/61 must be applied for updating tx
> handler: save update tx to local db only if TxId not empty

- handler/account.go
- handler/block.go
- handler/tx.go
- store/sync.go
Asana Link: https://app.asana.com/0/1125705697210963/1130269481966964
Cleanup connection to supervisor node in each handler.
> handler/store: cleanup connection to supervisor

- handler/account.go
- handler/block.go
- handler/tx.go
- store/sync.go
Reverts herdius/herdius-blockchain-api#73
> Revert "handler/store: cleanup connection to supervisor"

- server/server.go
> server: increase http read/write timeout

- store/migration/00004_increase_address_length.go
Asana Link: https://app.asana.com/0/1125705697210963/1130818234005886
Increase columns address length.
> store/migration: increase address length

- handler/account.go
> return empty opject instead of null

- handler/tx.go
> handler: fix missing nil checking in get locked txs

- server/server.go
> server: fix wrong checking conn test in db sync

- appspec.yml
- deployment/migrate.sh
Asana Link: https://app.asana.com/0/1125705697210963/1131484024511257
> deployment: add migrate script

- go.mod
- go.sum
Follow up https://github.com/herdius/herdius-core/pull/127
> update go module

- go.mod
- go.sum
- network/service.go
> network: refactor opcode types

- store/sync.go
Asana Link: https://app.asana.com/0/1125705697210963/1132230789322257
> store: remove wrong return in sync loop

- deployment/start_server.sh
Asana Link: https://app.asana.com/0/1125705697210963/1132023436522062
Use supervisord for service manager.
> deployment: use supervisor to manage service

- client.go
- cmd/account/main.go
As a part of account management, we need a way to publicly define as to how we generate herdius address.
This implementation has taken care of this.
Asana Link:
> Account management - Herdius Address Generation

- store/tx.go
> store: add missing tx type

- store/postgres/postgres.go
- store/postgres/postgres_test.go
> store/postgres: add missing type column

- store/postgres/postgres.go
- store/postgres/postgres_test.go
> store/postgres: update query to adopt data column

- handler/tx.go
Registration issue. PR in herdius-core: https://github.com/herdius/herdius-core/pull/193
Asana Link:
> Need to add register condition

- store/tx.go
> store: store empty string fo external addresses

- store/tx.go
> store: fix wrong external address for register tx

- handler/account.go
- handler/block.go
- handler/handler.go
- handler/tx.go
Notion Link: https://www.notion.so/herdius/Bad-response-from-HDKM-Gateway-Api-d942c2b67dd34dbcb838b026110f6a9c
Do not escape html in JSON response.
Passed.
> handler: do not escape html in JSON response

- handler/tx.go
- server/server.go
Asana Link: 
https://www.notion.so/herdius/Pending-tx-in-postgress-db-39ecbb0a42c9412a9738f737952a3d6c
> Sync if tx is in pending state
