herdius/herdius-blockchain-api

- .github/ISSUE_TEMPLATE.md
- README.md
- client.go
With our test chains currently deployed, we need our API and supported API actions to allow for different endpoints, as opposed to hardcoding `localhost`.
The `client` package is one such file that needs to allow for pointing to different API and chain endpoints.
Allow for `go run client.go` package to specify endpoint parameters.
```
❯ go run client.go 3.209.249.184
2019/04/05 11:14:40 endpoint: http://3.209.249.184:80/tx
2019/04/05 11:14:41
2019/04/05 11:14:41
```
Further document in `README`
> Allow client to specify endpoint

- config/config.go
- config/config.toml
- deployment/start_server.sh
- handler/account.go
- handler/block.go
- handler/tx.go
- network/service.go
The API server is currently hardcoded to expect that the Supervisor is running on `localhost` and complimentarily that the IP to broadcast to the network for P2P connections is `127.0.0.1`. This is very problematic for any situation where nodes need to be distributed (all non-dev envs).
Allow for environment setting through use of an `ENV` host environment variable.
To use the STAGING environment in the `config/config.toml`:
```
export ENV=staging
```
To use the DEV environment in the `config/config.toml`, use any other value or unset the environment variable completely.
Test in staging area.
* Do we now have a consistently connected API=>Supervisor=>API request-response cycle, via CICD pipeline? Can't test this until merged.
> allow for multiple environments

- network/service.go
The network dependencies in core have updated, but they haven't updated on the api server 
Update to provide the API server with the environment for network building
> Builder requires environment input

- README.md
- config/config.go
- handler/account.go
- handler/block.go
- handler/tx.go
- network/service.go
- server/server.go
We are transitioning the API Node to establish persistent connections with the Supervisor. However, the API nodes instead request new connections for every single inbound client request.
Establish a persistent connection with the Supervisor and allow all handles to use the same connection already established in order to make requests and receive responses.
```
❯ curl http://localhost:80/block/1
{1 1555506643 1 tcp://127.0.0.1:5555 []}%
```
```
❯ curl http://localhost:80/tx/HTx0a6a87494ab14872ebb5df2e9b0c939f12faef28
{"tx_id":"HTx0a6a87494ab14872ebb5df2e9b0c939f12faef28","tx":{"sender_address":"HDzLGL98C4vKtVWb3qzm92C2LX2V5kNhXR","sender_pubkey":"A72fjBMhMkDgP+DQJOkPEngf76Xar99JqjgzGkEGjBWh","reciever_address":"HPNMnZc9eNA7PzEMRWVqXwzPqieSRLzuyf","asset":{"category":"crypto","symbol":"HER", …
```
> Move peer connection to persist

- config/config.go
We broke our `master` branch with this change:
https://github.com/herdius/herdius-blockchain-api/pull/32/files#diff-3baf47c64847a8fb8aaa8cc2e088513bR31
Unbreak that change by making the config path, absolute.
```
❯ go run server/server.go -env=dev
2019/04/23 09:22:39 proto: duplicate proto type registered: protobuf.Timestamp
2019/04/23 09:22:39 proto: duplicate proto type registered: protobuf.ID
2019/04/23 09:22:39 proto: duplicate proto type registered: protobuf.ChildBlock
2019/04/23 09:22:39 proto: duplicate proto type registered: protobuf.Message
2019/04/23 09:22:39 proto: duplicate proto type registered: protobuf.Ping
2019/04/23 09:22:39 proto: duplicate proto type registered: protobuf.Pong
2019/04/23 09:22:39 proto: duplicate proto type registered: protobuf.LookupNodeRequest …
```
> Make config an absolute path instead of relative

- client.go
- deployment/start_server.sh
1. Logging on remote machines is useless, as the current logging mechanism is to `/dev/null` for both stdout and stderr. Logging is important for us to be able to view for debugging issues.
2. The `client.go` file only POSTs a single transaction, making bulk transaction sending tedious.
1. Log all server output to a file in `/var/log/herdius/herdius-blockchain-api/log/server.log` including both stdout and stderr. Delete this file upon new server start, so as to not fill disk space on API node.
2. Post 30 new tx's with different nonce values for the `client.go` file.
```
[root@ip-10-0-0-34 herdius-blockchain-api]# cat /var/log/herdius/herdius-blockchain-api/log/server.log | wc -l
19
[root@ip-10-0-0-34 herdius-blockchain-api]# cat /var/log/herdius/herdius-blockchain-api/log/server.log | wc …
```
> client.go send multiple txs; logging to file not stdout

- client.go
Value transfer implementation logic is modified in [herdius-core](https://github.com/herdius/herdius-core/pull/43)  for external assets according to JSON object representation of account state in herdius blockchain. So need a go client to send external transactions.
Asana Link:
[Problem description in Asana](https://app.asana.com/0/998359196895599/1123326413582231)
Asana Link: 
Created a method that sends external transactions.
To run it execute the below command.
`go run client.go -txtype=external`
> added a method to send external transactions

- handler/block.go
Right now when block detail is enquired through a rest endpoints, it gives a reply without the field names. 
A proper JSON response has to be returned when block details are provided to end users.
Asana Link: 
https://app.asana.com/0/998359196895599/1120852002402144
Provided a way to get the block details respond in JSON format
{
"blockHeight": 4,
"timestamp": 1558516185,
"transactionsCount": 1,
"supervisorIP": "tcp://127.0.0.1:5555",
"stateRoot": "ERz/nB2F60jSRPzcSED8/yCrs7YSe9aH8Fd7VPm15hY="
}
> Block response in JSON format

- config/config.go
Wrong usage of viper.Get* for db port and ssl mode.
Use right methods.
> config: fix wrong viper get type

- README.md
- appspec.yml
- client.go
The API server attempts to launch destroy the old API, and launch the new API, via `start_server.sh`. However, it doesn't have adequate permissions to execute this file.
Implement the same solution with the same solutions as is done in the [Supervisor repo](https://github.com/herdius/herdius-core/blob/master/appspec.yml#L7).
Watch it successfully execute in staging.
> update perms and readme

- handler/db.go
getStore intends to set db only if NewStore returns no error. But in
case of error, it returns a store.Storer also, causing db is set to
non-nil.
Asana Link:
> handler: fix getStore

- store/tx.go
Convert from protobuf TX to store TX is returning nil.
Should return tx, the `nil` is from the first skeleton code.
Passed.
> store: fix wrong return tx

- handler/tx.go
API panic when post tx return failed from core
Save when tx id not empty, mean calling to core success.
Passed.
> handler: save tx to local db only if tx id not empty

- handler/tx.go
- server/server.go
- store/postgres/postgres.go
- store/store.go
- store/sync.go
- store/tx.go
Posted TX won't be available in core immediately, so saving it to local DB right after API call is not doable.
Save posted TX as pending state in local database, spawn a separate goroutine to update these txs.
> handle store posted tx in separate goroutine

- handler/account.go
Since block may takes times to be processed in core, get account may
returns nil, causing len check panic.
Check account is nil first fixes the panic.
> handler: check account is nil first

- server/server.go
Get lock txs url path is overlapping with get txs by address.
Change get lock txs url path.
> server: fix lock tx url path overlapping

- server/server.go
Another fix after PR #68 
Use another url path.
> server: fix lock tx url path overlapping again

- handler/tx.go
Current url path param var name is `blockNumber`, which is wrong.
Use the right var name `block_number`.
> handler: fix wrong url path param variable

- network/service.go
Get lock txs failed with error `failed to get locked txs due to: types: message type not found, did you register it?`
Register missing proto messages.
> network: fix missing register lock tx proto

- server/server.go
Server does not catch sigterm, which is currently used in deploy script.
> server: catch sigterm

- store/migration/00005_tx_type.go
2019/07/15 14:55:03 goose up: ERROR 00005_tx_type.go: failed to run Go migration function func(*sql.Tx) error: pq: syntax error at or near "VARCHAR"
Asana Link:
> Migration Error fix

- server/server.go
> server: log if not connected to core when syncing pending txs

- go.mod
- go.sum
- server/server.go
Missing discovery plugin causes api failed to reconnect to supervisor
when supervisor node restart. This happens due to api continue using the
underlying dead connection, causing write broken pipe error.
Add the discovery plugin fixes the issue.
Asana Link: https://app.asana.com/0/1125705697210963/1134857550854831
Add missing discovery plugin.
`go run client.go -txtype=all` passed.
> server: add missing discovery plugin

- client.go
When reading transactions from blockchain server and blockchain api **tx-type** field is missing due to which we are not able to check the transaction type in other services. This works fine in locally. Just trying to make a new build and deploy to check if this could be solved.
[
{
"tx_id": "HTxc3f069a8abad725956a1fd04b018d9a0570d7a0b",
"tx": {
"sender_address": "HKbejAN57Z2qZAqbUcCurEmF8CxHU5UFe1",
"sender_pubkey": "Arm8qBVmluU74W2d7Xp8NOQL5tejh1fP7H9LApRJvYuU",
"asset": {
"category": "crypto",
"symbol": "HER",
"network": "Herdius"
},
"message": "Register New HER Account",
"sign": "9FrzQBToveo39K9kU4uydkj8wSWhVQRaAKDOiiO89/44EWzvNfQ1859ucZRHbOhAuiIeo2dSa+5v7L5bD/0bAA==",
**"type": "update",**
"status": "success"
},
"creationDt": {
"seconds": 1567410092,
"nanos": 1567410092279360000
}, …
> Just a placeholder change to check the tx type in db
